<?php

module_load_include('inc', 'objective_forms', 'Form');

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 * @return string
 */
function handsontable_help($path) {
  switch ($path) {
    case "admin/help#handsontable":
      return '<p>' . t("Adding Handsontable widget to Islandora XML forms") . '</p>';
      break;
  }
  return '';
}

/**
 * Implements hook_element_info()
 *
 * Adds the handsontable element to the form elements
 */
function handsontable_element_info() {
  $types['handsontable'] = array(
    '#input' => TRUE,
    '#process' => array('handsontable_tag_process'),
    '#theme_wrappers' => array('handsontable', 'form_element'),
  );

  $types['handsontable_row'] = array(
    '#input' => TRUE,
    '#process' => array('handsontable_row_tag_process'),
    '#theme' => array('handsontable_row'),
  );
  return $types;
}

/**
 * Implements hook_theme().
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function handsontable_theme($existing, $type, $theme, $path) {
  return [
    'handsontable' => [
      'render element' => 'element',
      'file' => 'Handsontable.inc',
    ],
    'handsontable_row' => [
      'render element' => 'element',
      'file' => 'HandsontableRow.inc',
    ],
  ];
}

/**
 * Process a handsontable tag
 */
function handsontable_tag_process($element, &$form_state, $complete_form) {
  form_load_include($form_state, 'inc', 'handsontable', 'Handsontable');
  return Handsontable::process($element, $form_state, $complete_form);
}

/**
 * Process a handsontable row tag
 */
function handsontable_row_tag_process($element, &$form_state, $complete_form) {
  form_load_include($form_state, 'inc', 'handsontable', 'HandsontableRow');
  return HandsontableRow::process($element, $form_state, $complete_form);
}


/**
 * This function is triggered from objective_forms Form::ajaxAlter() from the addRow callback
 *
 * @param FormElement $element
 * @param array $form
 * @param array $form_state
 * @return bool
 */
function handsontable_form_element_handsontable_ajax_alter(FormElement $element, array &$form, array &$form_state) {

  // Either remove or add rows
  $rows = $form_state['values'][$element->getIndex()]['rows'] - 1;
  $children = count($element->children);

  $diff = $rows - $children;

  if ( $diff > 0 ) {
    do {
      $new = clone $element->children[0];
      $new->eachDecendant(function($element) {
        $element->default_value = NULL;
      });
      $element->adopt($new);
      $form[] = $new->toArray();

      $diff--;
    } while ( $diff > 0);
  }
  elseif ($diff < 0) {
    do {
      // TODO: The removal of rows is not called at the moment. Because handsontable
      // does not reduce the number of rows
      $last = end($element->children);
      $last->orphan();
      unset($form[count($element->children)]);

      $diff++;
    } while ( $diff < 0);
  }

  return TRUE;
}
